[package]
name = "swc-plugin-rask-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
swc_core = { version = "47", features = [
  "swc_atoms",
  "swc_common",
  "transform_common",
  "swc_ecma_ast",
  "ecma_plugin_transform",
  "ecma_utils",
  "ecma_visit",
  "ecma_ast",
  "common",
] }

[profile.release]
# This removes more dead code
codegen-units = 1
lto = true
# Optimize for size
opt-level = "z"
# Optimization for WASM
panic = "abort"
